### PR TITLE
Get the C++ standard from root-config to keep the consistencies between GenFit and ROOT and fixed the eigen URL in CI

### PR DESCRIPTION
**Pull request by mirguest**
Dear GenFit developers,

I am Tao Lin from IHEP, working on the [CEPCSW](https://github.com/cepc/CEPCSW). 
Currently we try to build GenFit with LCG release. The problem I found is the ROOT 6 is built with c++17 in LCG release, which will cause following problem:
```bash
Singularity> cmake ../GenFit-src/
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /cvmfs/sft.cern.ch/lcg/releases/gcc/8.3.0-cebb0/x86_64-slc6/bin/gcc
-- Check for working C compiler: /cvmfs/sft.cern.ch/lcg/releases/gcc/8.3.0-cebb0/x86_64-slc6/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /cvmfs/sft.cern.ch/lcg/releases/gcc/8.3.0-cebb0/x86_64-slc6/bin/g++
-- Check for working CXX compiler: /cvmfs/sft.cern.ch/lcg/releases/gcc/8.3.0-cebb0/x86_64-slc6/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found global svn revision to be exported
.
-- Check for ROOT_CONFIG_EXECUTABLE: /cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/bin/root-config
-- Check for ROOT_EXECUTABLE: /cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/bin/root
-- Check for ROOT_CINT_EXECUTABLE: /cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/bin/rootcling
-- Check for libdl.so: /usr/lib64/libdl.so
-- No RAVEPATH or Rave flags given. GFRave will not be built.
CPP STANDARD: c++11
-- Found Doxygen: /cvmfs/sft.cern.ch/lcg/views/LCG_97/x86_64-slc6-gcc8-opt/bin/doxygen (found version "1.8.15") found components:  doxygen dot
-- Found GTest: /cvmfs/sft.cern.ch/lcg/views/LCG_97/x86_64-slc6-gcc8-opt/lib64/libgtest.a
-- /cvmfs/sft.cern.ch/lcg/views/LCG_97/x86_64-slc6-gcc8-opt/include
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/lint/genfit/GenFit-build3

Singularity> make
[  1%] Generating coreRootDict.cc, coreRootDict_rdict.pcm, coreRoot.rootmap
[  2%] Generating utilitiesRootDict.cc, utilitiesRootDict_rdict.pcm, utilitiesRoot.rootmap
[  3%] Generating trackRepsRootDict.cc, trackRepsRootDict_rdict.pcm, trackRepsRoot.rootmap
[  4%] Generating measurementsRootDict.cc, measurementsRootDict_rdict.pcm, measurementsRoot.rootmap
[  6%] Generating GBLRootDict.cc, GBLRootDict_rdict.pcm, GBLRoot.rootmap
[  7%] Generating fittersRootDict.cc, fittersRootDict_rdict.pcm, fittersRoot.rootmap
[  8%] Generating eventDisplayRootDict.cc, eventDisplayRootDict_rdict.pcm, eventDisplayRoot.rootmap
Scanning dependencies of target genfit2
[  9%] Building CXX object CMakeFiles/genfit2.dir/utilitiesRootDict.cc.o
In file included from /cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TString.h:28,
                 from /cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TNamed.h:26,
                 from /cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TDictionary.h:44,
                 from /cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TClass.h:23,
                 from /tmp/lint/genfit/GenFit-build3/utilitiesRootDict.cc:14:
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/ROOT/RStringView.hxx:84:17: error: expected type-specifier
        operator std::string_view() const { return std::string_view(fData,fLength); }
                 ^~~
In file included from /cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TNamed.h:26,
                 from /cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TDictionary.h:44,
                 from /cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TClass.h:23,
                 from /tmp/lint/genfit/GenFit-build3/utilitiesRootDict.cc:14:
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TString.h:110:13: error: expected type-specifier
    operator std::string_view() const { return std::string_view(Data(),fExtent); }
             ^~~
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TString.h:275:32: error: ‘string_view’ in namespace ‘std’ does not name a type
    explicit TString(const std::string_view &sub);
                                ^~~~~~~~~~~
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TString.h:275:27: note: ‘std::string_view’ is only available from C++17 onwards
    explicit TString(const std::string_view &sub);
                           ^~~
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TString.h:312:37: error: ‘string_view’ in namespace ‘std’ does not name a type
    TString    &operator=(const std::string_view &s);
                                     ^~~~~~~~~~~
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TString.h:312:32: note: ‘std::string_view’ is only available from C++17 onwards
    TString    &operator=(const std::string_view &s);
                                ^~~
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TString.h:439:9: error: ‘string_view’ in namespace ‘std’ does not name a type
    std::string_view View() const { return std::string_view(GetPointer(),Length()); }
         ^~~~~~~~~~~
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TString.h:439:4: note: ‘std::string_view’ is only available from C++17 onwards
    std::string_view View() const { return std::string_view(GetPointer(),Length()); }
    ^~~
In file included from /cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TNamed.h:26,
                 from /cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TDictionary.h:44,
                 from /cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TClass.h:23,
                 from /tmp/lint/genfit/GenFit-build3/utilitiesRootDict.cc:14:
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TString.h:834:53: error: ‘string_view’ in namespace ‘std’ does not name a type
 inline Bool_t operator==(const char *s1, const std::string_view &s2)
                                                     ^~~~~~~~~~~
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TString.h:834:48: note: ‘std::string_view’ is only available from C++17 onwards
 inline Bool_t operator==(const char *s1, const std::string_view &s2)
                                                ^~~
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TString.h:834:68: error: ‘Bool_t operator==(const char*, const int&)’ must have an argument of class or enumerated type
 inline Bool_t operator==(const char *s1, const std::string_view &s2)
                                                                    ^
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TString.h:839:37: error: ‘string_view’ in namespace ‘std’ does not name a type
 inline Bool_t operator==(const std::string_view &s1, const char *s2)
                                     ^~~~~~~~~~~
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TString.h:839:32: note: ‘std::string_view’ is only available from C++17 onwards
 inline Bool_t operator==(const std::string_view &s1, const char *s2)
                                ^~~
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TString.h:839:68: error: ‘Bool_t operator==(const int&, const char*)’ must have an argument of class or enumerated type
 inline Bool_t operator==(const std::string_view &s1, const char *s2)
                                                                    ^
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TString.h:852:37: error: ‘string_view’ in namespace ‘std’ does not name a type
   std::string printValue(const std::string_view* val);
                                     ^~~~~~~~~~~
/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include/TString.h:852:32: note: ‘std::string_view’ is only available from C++17 onwards
   std::string printValue(const std::string_view* val);
                                ^~~
make[2]: *** [CMakeFiles/genfit2.dir/utilitiesRootDict.cc.o] Error 1
make[1]: *** [CMakeFiles/genfit2.dir/all] Error 2
make: *** [all] Error 2

```

In order to fixed the problem, I have a bit modification on the CMakeLists.txt to allow specifying the c++ standard.
To specify the c++17, just run cmake with option `-DCPP_STANDARD=c++17`:
```
Singularity> cmake ../GenFit-src/ -DCPP_STANDARD=c++17
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /cvmfs/sft.cern.ch/lcg/releases/gcc/8.3.0-cebb0/x86_64-slc6/bin/gcc
-- Check for working C compiler: /cvmfs/sft.cern.ch/lcg/releases/gcc/8.3.0-cebb0/x86_64-slc6/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /cvmfs/sft.cern.ch/lcg/releases/gcc/8.3.0-cebb0/x86_64-slc6/bin/g++
-- Check for working CXX compiler: /cvmfs/sft.cern.ch/lcg/releases/gcc/8.3.0-cebb0/x86_64-slc6/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found global svn revision to be exported
.
-- Check for ROOT_CONFIG_EXECUTABLE: /cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/bin/root-config
-- Check for ROOT_EXECUTABLE: /cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/bin/root
-- Check for ROOT_CINT_EXECUTABLE: /cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/bin/rootcling
-- Check for libdl.so: /usr/lib64/libdl.so
-- No RAVEPATH or Rave flags given. GFRave will not be built.
CPP STANDARD: c++17
-- Found Doxygen: /cvmfs/sft.cern.ch/lcg/views/LCG_97/x86_64-slc6-gcc8-opt/bin/doxygen (found version "1.8.15") found components:  doxygen dot
-- Found GTest: /cvmfs/sft.cern.ch/lcg/views/LCG_97/x86_64-slc6-gcc8-opt/lib64/libgtest.a
-- /cvmfs/sft.cern.ch/lcg/views/LCG_97/x86_64-slc6-gcc8-opt/include
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/lint/genfit/GenFit-build3

```

### CODE REVIEW

**Comment by mirguest** [comment]
As the eigen moves from bitbucket to gitlab, the URL pointing to bitbucket is not valid any more. Please see the commit af50b29d00790d39f093e0e732480453893493d5

**Comment by olifre** [comment]
While not a GenFit maintainer myself. I think the cpp standard issue can be resolved in a cleaner manner with #60, which inherits the C++ standard from ROOT automatically. This is also the established approach used by other ROOT-based libraries such as VGM, VMC and geant-vmc and follows the approach that the build system should always choose a working configuration by default.

**Comment by nils-braun** [comment]
First of all, thank you @mirguest for the changes!

Would you @mirguest or @olifre  be open to implement the proposed changes by @olifre?

**Comment by olifre** [comment]
@nils-braun I personally will not have time this month at least, but could probably have a look into this next month. It's not completely straightforward, since the simple migration of the CMake commands may cause side effects such as (see the first comment for the actual "migration commit"):
https://github.com/vmc-project/geant4_vmc/issues/13

These can be solved as was done in the course of that issue, but it requires some testing to check if relocatability is kept and no bad runtime dependencies from the PCMs are added. Of course, if somebody starts on the migration to upstream's `FindROOT.cmake`, I can surely find time earlier to perform some of the necessary testing.

**Comment by eckerpatrick** [comment]
@olifre do you have any updates on the solution you proposed?
If not I suggest using the solution provided by @mirguest until there is a cleaner one.

**Comment by olifre** [comment]
@eckerpatrick Since I have been flooded with development for other projects, sadly not yet. 
Of course, if the fix is urgent, using the solution discussed here would be possible. But it's clear this will break GenFit on many platforms by default, too, and actually may even produce obscure runtime errors if the user does not specify the CPP standard to match the one ROOT is using. 
I leave the decision to the developers and will come back to this once I have the spare time to work on it.

**Comment by olifre** [comment]
I had a very quick look at this and it seems this is an even larger effort than expected — it requires quite some refactoring of the current CMake code, since at the moment, GenFit builds several separate dictionaries, which does not allow for a clean implementation. 
To my understanding, the expectation is: For each library, there is one PCM and one (potentially merged) dictionary. 

Refactoring things this way will definitely shorten the current implementation heavily, but requires more time than I currently have (but it needs to be done).

**Comment by eckerpatrick** [comment]
@olifre thanks for your fast reply and checking this.
I think the last thing we want to do is break GenFIt on other platforms.

Therefore I suggest that maybe @mirguest you can find a workaround for this in your project?

**Comment by MarkusPrim** [comment]
> As the eigen moves from bitbucket to gitlab, the URL pointing to bitbucket is not valid any more. Please see the commit [af50b29](https://github.com/GenFit/GenFit/commit/af50b29d00790d39f093e0e732480453893493d5)

I think eigen can actually be removed from the project as the implementations in eigen are not used in any code which is run. Using eigen was an attempt to improve the code base but never finished due to lack of time.
This would remove a dependency, should be straightforward, and make everyones life easier (except for the person to actually remove it).

**Comment by mirguest** [comment]
Hi @eckerpatrick and @olifre,
Sorry for the late reply.

I don't think this PR will break the GenFit. With this PR, users are allowed to override the default `CPP_STANDARD`. If they don't specify any option, then the default `CPP_STANDARD` is always `c++11`. 

If you are worrying about the break due to this option, let's introduce a new option, such as `GENFIT_CPP_STANDARD`. 
Do you think is that fine for you?

Tao

**Comment by mirguest** [comment]
Key4HEP project provides the common software for the future collider experiments (ILC, FCC, CEPC...). The spack is adopted to manage all the packages: https://github.com/key4hep/key4hep-spack

Because GenFit2 is used in CEPCSW, it is necessary to install GenFit2 via spack. That's why we also hope there could be a first release.

Thank you.

Tao

**Comment by olifre** [comment]
> I don't think this PR will break the GenFit. With this PR, users are allowed to override the default `CPP_STANDARD`. If they don't specify any option, then the default `CPP_STANDARD` is always `c++11`.

You are of course correct that it will not be broken more than it currently is, it will just be easier for users to break it. Exposing the option is misleading, since this is not something which should be configured by the user: The `CPP_STANDARD` used by GenFit _must_ match the `CPP_STANDARD` used by ROOT, otherwise you will encounter build errors (or in some cases, runtime errors, or build errors of dependent libraries). 

For this reason, this is not configurable in `geant-vmc`, `vmc`, `vgm`, and other libraries which are linking against ROOT (and / or Geant). 

If it is very urgent for you, I could prepare a "hackish" version which inherits the C++ standard from ROOT without rewriting all of the CMake code used by GenFit. This would not be the necessary cleanup (and usage of ROOTs CMake code), but a fix of the current situation, and the better fix involving a larger rewrite could be left as a future exercise. 

What do you all think about this?

**Comment by olifre** [comment]
Hi @mirguest ,

indeed, your implementation looks exactly as what I had in mind when I mentioned inheriting the version from ROOT without refactoring the CMake code in full :+1: . 

So indeed I fully agree with the new solution as the minimalistic approach. Switching to `ROOTConfig.cmake` is also due, but might be better done separately. 

Thanks!

**Comment by mirguest** [comment]
Thanks @olifre for your review!
Tao

**Comment by MarkusPrim** [comment]
Just for reference, there is issue #60 for the ROOT cmake update.

**Comment by mirguest** [comment]
The conflict in .travis.ci.yaml is resolved. 
Tao

**Comment by MarkusPrim** [comment]
> The conflict in .travis.ci.yaml is resolved.
> Tao

Thanks for that!

**Comment by eckerpatrick** [comment]
@mirguest thanks a lot for your changes!

**Pull request merged**
