### PR TITLE
Fixed some cppcheck warnings

### PR DESCRIPTION
**Pull request by GiacomoXT**
I fixed some cppcheck warnings (the ones offending the basf2 klm package). These are rather trivial fixes. :)

### CODE REVIEW

**Comment by GiacomoXT** [comment]
@MarkusPrim these are the modifications I mentioned via mail.

**Comment by MarkusPrim** [comment]
@eckerpatrick is the current GenFit librarian. I forgot to mention this in the email

**Comment by nils-braun** [comment]
@eckerpatrick LGTM from my side :-)
@GiacomoXT Thanks for fixing this!

**Comment by GiacomoXT** [comment]
I took the freedom to fix few other trivial warnings. I won't fix other things, promised.

**Comment by GiacomoXT** [comment]
> Looks good, thanks for making this changes

How does it work here for merging the PR? I don't see any button, so I think you have the privilege for this (or maybe, it's a privilege of Markus-san or Nils-san).

**Pull request merged**
