### PR TITLE
Replace NULL with nullptr everywhere.

### PR DESCRIPTION
**Pull request by MarkusPrim**
Because of e.g. this: https://stackoverflow.com/questions/20509734/null-vs-nullptr-why-was-it-replaced
I experienced the ambiguous overloading during some local testing. There is no reason to keep the NULL and not switch to nullptr.

### CODE REVIEW

**Comment by MarkusPrim** [comment]
Woops. I will close this and find out where this comes from.

**Comment by nils-braun** [comment]
Nevertheless, I think it is a valid request...

**Comment by MarkusPrim** [comment]
Yes. Also with ROOT6 this passes the build. I will reopen this as soon as we use ROOT6 in our CI.

**Comment by ThomasHauth** [comment]
I merged the ROOT6 CI pull request and will reopen this PR.

**Pull request merged**
