### PR TITLE
cmake: Use the upstream root macros for dictionary generation

### PR DESCRIPTION
**Pull request by tmadlener**
Genfit stopped building against root 6.30.02 for me, because the version determination didn't work any longer. (I am not sure what has changed upstream to break that). Since root brings its own cmake find support and also has its own macros for dictionary generation I also switched those over. Finally, I fixed a few `target_link_libraries` to use targets provided by ROOT.

I bumped the minimum root version to 6.20, because at that point the macros should be stable enough to work reliably. Also that has been around for quite some time now, so I think it is safe to do so.

### CODE REVIEW

**Comment by eckerpatrick** [comment]
Thank you very much @tmadlener for spotting and fixing this.
To avoid this in the future I adapted the pipeline to also build with the new ROOT version (https://github.com/GenFit/GenFit/pull/128).
Could you merge the new main into your branch for testing?

**Comment by tmadlener** [comment]
Rebased this onto latest master. It seems that the breaks in CI are unrelated to the changes here(?)

**Comment by tmadlener** [comment]
OK. Looks like the 6.24 job was killed because the 6.30 job was failing due to missing `xxhash` in the test environment. Should both be fixed now.

**Comment by tmadlener** [comment]
Looks like there were a few more dependencies missing for ROOT 6.30. Now we should have all of them :crossed_fingers:

**Comment by eckerpatrick** [comment]
Excellent, thanks a lot for adding the missing dependencies.

**Comment by tmadlener** [comment]
Would it be possible to get a new tag / release that include these changes? That would make them easier to pick them up for us.

**Comment by eckerpatrick** [comment]
> Would it be possible to get a new tag / release that include these changes? That would make them easier to pick them up for us.

Done

**Pull request merged**
